# Go to http://localhost:8000/api/users/login/ and login as admin to get an admin token,
# or as a user to get a normal authentication token.

# Variables
@URL = http://127.0.0.1:8000/api

# All products
GET {{URL}}/products/

###

# One product

GET {{URL}}/products/14

###

GET {{URL}}/users/profile/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1MTU1MzE0LCJqdGkiOiIzNDFkZjhlMjEzM2U0NjIxOWExOWVhOTA0YjQyNTgyOSIsInVzZXJfaWQiOjF9.XsLYlsTEv4uFJh0985hfPQPSZQQWNCxLbS3XjuVXjeA

###

GET {{URL}}/users/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1MTU1MzE0LCJqdGkiOiIzNDFkZjhlMjEzM2U0NjIxOWExOWVhOTA0YjQyNTgyOSIsInVzZXJfaWQiOjF9.XsLYlsTEv4uFJh0985hfPQPSZQQWNCxLbS3XjuVXjeA

###

POST {{URL}}/users/register/
Content-Type: application/x-www-form-urlencoded

name=Carla
&email=carla@gmail.com
&password=123123

###

PUT {{URL}}/users/profile/update/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1MzA5NjYyLCJqdGkiOiJjZTViOTc1YmRmNzg0NzdmYjlhMzg1ZTAxZWMyOGRmYSIsInVzZXJfaWQiOjN9.weDFeS1mW-w0B7HH258KaLr9xCK7vKXgKumClz0BOKY
Content-Type: application/x-www-form-urlencoded

name=Carla
&email=carla@gmail.com
&password=123123

###

# The following one with json formatted data, does the same as above.
PUT {{URL}}/users/profile/update/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1MzA5NjYyLCJqdGkiOiJjZTViOTc1YmRmNzg0NzdmYjlhMzg1ZTAxZWMyOGRmYSIsInVzZXJfaWQiOjN9.weDFeS1mW-w0B7HH258KaLr9xCK7vKXgKumClz0BOKY
Content-Type: application/json

{
    "name": "Carla",
    "email":"carla@gmail.com",
    "password":""
}

###

GET {{URL}}/orders/6/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1MzY2ODU2LCJqdGkiOiI3Nzc2Y2UyNjliYWI0YTM5YmI5YmMxYjQ5OGE4Mzg5ZSIsInVzZXJfaWQiOjF9.Sp8hOyFp0suQALk4A-xEEEwNLcx7vb2_SOAMD085vt0

###

# Get my orders
GET {{URL}}/orders/myorders/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1MzY2ODU2LCJqdGkiOiI3Nzc2Y2UyNjliYWI0YTM5YmI5YmMxYjQ5OGE4Mzg5ZSIsInVzZXJfaWQiOjF9.Sp8hOyFp0suQALk4A-xEEEwNLcx7vb2_SOAMD085vt0

###

# Delete User

DELETE {{URL}}/users/delete/2/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1MzY2ODU2LCJqdGkiOiI3Nzc2Y2UyNjliYWI0YTM5YmI5YmMxYjQ5OGE4Mzg5ZSIsInVzZXJfaWQiOjF9.Sp8hOyFp0suQALk4A-xEEEwNLcx7vb2_SOAMD085vt0

###

# Get User by Id

GET {{URL}}/users/3/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1MzY2ODU2LCJqdGkiOiI3Nzc2Y2UyNjliYWI0YTM5YmI5YmMxYjQ5OGE4Mzg5ZSIsInVzZXJfaWQiOjF9.Sp8hOyFp0suQALk4A-xEEEwNLcx7vb2_SOAMD085vt0

###

# Update user
PUT {{URL}}/users/update/3/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1NTY0NjE1LCJqdGkiOiI3ZTFjODU5YzVhMDE0MWFjYTM5NzA4YWI3MmY0MTU2MCIsInVzZXJfaWQiOjF9.rejoQispeM4enDYVydrnKmpEyBBwU5s2Oqg_cKWubL4
Content-Type: application/json

{
    "name": "Carla",
    "email": "carla@gmail.com",
    "isAdmin": false
}

###

# Delete Product
DELETE {{URL}}/products/delete/9
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1NTY0NjE1LCJqdGkiOiI3ZTFjODU5YzVhMDE0MWFjYTM5NzA4YWI3MmY0MTU2MCIsInVzZXJfaWQiOjF9.rejoQispeM4enDYVydrnKmpEyBBwU5s2Oqg_cKWubL4

###

# Create product (with default values)

POST {{URL}}/products/create/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1NTY0NjE1LCJqdGkiOiI3ZTFjODU5YzVhMDE0MWFjYTM5NzA4YWI3MmY0MTU2MCIsInVzZXJfaWQiOjF9.rejoQispeM4enDYVydrnKmpEyBBwU5s2Oqg_cKWubL4

###
PUT {{URL}}/products/update/10/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1NTY0NjE1LCJqdGkiOiI3ZTFjODU5YzVhMDE0MWFjYTM5NzA4YWI3MmY0MTU2MCIsInVzZXJfaWQiOjF9.rejoQispeM4enDYVydrnKmpEyBBwU5s2Oqg_cKWubL4
Content-Type: application/json

{
    "name": "Amazing product",
    "price": 123,
    "brand": "Brack tech",
    "countInStock": 8,
    "category": "Electronics",
    "description": "Really amazing"
}

###

# Get orders (For admins)

GET {{URL}}/orders/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1NTY0NjE1LCJqdGkiOiI3ZTFjODU5YzVhMDE0MWFjYTM5NzA4YWI3MmY0MTU2MCIsInVzZXJfaWQiOjF9.rejoQispeM4enDYVydrnKmpEyBBwU5s2Oqg_cKWubL4

###

# Update order to delivered (For admins)

PUT {{URL}}/orders/14/deliver/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1NTY0NjE1LCJqdGkiOiI3ZTFjODU5YzVhMDE0MWFjYTM5NzA4YWI3MmY0MTU2MCIsInVzZXJfaWQiOjF9.rejoQispeM4enDYVydrnKmpEyBBwU5s2Oqg_cKWubL4

###

# Create review

POST {{URL}}/products/1/reviews/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjE1NTY0NjE1LCJqdGkiOiI3ZTFjODU5YzVhMDE0MWFjYTM5NzA4YWI3MmY0MTU2MCIsInVzZXJfaWQiOjF9.rejoQispeM4enDYVydrnKmpEyBBwU5s2Oqg_cKWubL4
Content-Type: application/json

{
    "rating": 1,
    "comment": "Meh"
}
